### ISSUE TITLE
Modularize React questionnaire code

### ISSUE THREAD

**Issue by jaredigms** [CitizenHealth/COVIDx#15]
# Description
* We should be able to add and edit survey and question content/styles without needing to touch the React code.
* Having this in place should make updating the survey much easier and remove React as a barrier to creating surveys.
# Acceptance Criteria
- [ ] Questionnaire content and questionnaire React code exist as two separate files

**Comment by Murkantilism** [comment]
@jaredigms this might be addressed completely if we switch from React native forms to something else, as @BrennenHodge and I talked about [here](https://github.com/CitizenHealth/COVIDx/issues/14#issuecomment-624156633).

Although no decision has been made, it would be prudent not to start this sort of effort until we decide for sure to stick to native since this isn't a trivial refactor it seems like, though not terribly hard either.

**Comment by jaredigms** [comment]
Closing due to shit to Tripetto
